
import Navbar from "@/components/Navbar";
import "./globals.css";
import AdminLayout from "./admin/layout";
import { cookies } from "next/headers";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {


   const cookieStore = await cookies(); // ✅ Correct
  const authToken = cookieStore.get("auth-token")?.value;

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/img/logo.png" alt="logo" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <>
        <body className="font-poppins">
          {authToken ? (
            <></>
          ) : (
            <>
              <Navbar />
            </>
          )}
          {children}
          {authToken ? (
            <></>
          ) : (
            <>
                <Footer/>
            </>
          )}
        </body>
      </>
    </html>
  );
}
